spring.application.name=dms

spring.datasource.url=jdbc:mysql://localhost:3306/dms_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:116081Gb.}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=hyundaihyundaihyundaihyundaihyundai1234efvcevcececececefce4rcerwevc56tgy6tbv5
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:3000
